// Pick the Noto Serif TC unicode-range subsets that Q7's Chinese strings need,
// and write src/q7/cjkFaces.ts (static imports → only those woff2 files are bundled).
//   node scripts/cjk-subsets.mjs        (run in paper/; rerun after editing src/q7/i18n/zh.ts, ext.zh.ts or card.ts)
//
// Chinese is set in the stack 'EB Garamond', 'Noto Serif TC': a character the
// bundled Garamond cut (its latin subset) draws never reaches Noto. Every other
// character of the zh table's prose (TeX in $…$ excluded — MathJax draws that)
// must be covered by a bundled Noto subset. A string with no Chinese in it is an
// English placeholder: an uncovered character there is only warned about.
import fs from "node:fs";
import path from "node:path";

const WEIGHTS = ["400", "500", "600"]; // body / titles + tracked labels / emphasis ({i:…})
const PKG = "node_modules/@fontsource/noto-serif-tc";
const SOURCES = ["src/q7/i18n/zh.ts", "src/q7/i18n/ext.zh.ts", "src/q7/i18n/card.ts"];

const parseRange = (s) =>
  s.split(",").map((r) => {
    const [a, b] = r.trim().replace(/^U\+/i, "").split("-");
    return [parseInt(a, 16), parseInt(b ?? a, 16)];
  });
const inSpans = (cp, spans) => spans.some(([lo, hi]) => cp >= lo && cp <= hi);

// the Garamond cut fonts.ts bundles
const latinCss = fs.readFileSync("node_modules/@fontsource/eb-garamond/400.css", "utf8");
const LATIN_RANGE = /eb-garamond-latin-400-normal\.woff2[\s\S]*?unicode-range:\s*([^;]+);/.exec(latinCss)[1].trim();
const LATIN = parseRange(LATIN_RANGE);

// string literals of the zh table (comments stripped; the tables use "…" only)
const CJK = /[⺀-鿿豈-﫿︰-﹏＀-￯]/;
const strings = SOURCES.flatMap((f) => {
  const src = fs.readFileSync(f, "utf8").replace(/\/\*[\s\S]*?\*\//g, "").replace(/^\s*\/\/.*$/gm, "");
  return [...src.matchAll(/"((?:[^"\\\n]|\\.)*)"/g)].map((m) => JSON.parse(`"${m[1]}"`));
});
const strict = new Set();
const loose = new Set();
for (const s of strings) {
  const prose = s.replace(/\$[^$]*\$/g, "");
  for (const c of prose) {
    const cp = c.codePointAt(0);
    if (inSpans(cp, LATIN)) continue;
    (CJK.test(s) ? strict : loose).add(c);
  }
}
const chars = [...new Set([...strict, ...loose])].sort();

const out = [];
const warned = new Set();
for (const w of WEIGHTS) {
  const css = fs.readFileSync(path.join(PKG, `${w}.css`), "utf8");
  const blocks = [...css.matchAll(/url\(\.\/files\/([^)]+?\.woff2)\)[\s\S]*?unicode-range:\s*([^;]+);/g)].map((m) => ({
    file: m[1],
    range: m[2].trim(),
    spans: parseRange(m[2]),
  }));
  const need = new Map();
  for (const c of chars) {
    const cp = c.codePointAt(0);
    const b = blocks.find((b) => inSpans(cp, b.spans));
    if (!b) {
      if (strict.has(c)) throw new Error(`no Noto Serif TC ${w} subset covers "${c}" (U+${cp.toString(16)}) — set it in TeX or drop it`);
      if (!warned.has(c)) console.warn(`  warning: "${c}" (U+${cp.toString(16)}) in an English placeholder is not covered by Noto — system fallback until translated`);
      warned.add(c);
      continue;
    }
    need.set(b.file, b);
  }
  for (const b of need.values()) out.push({ w, ...b });
}

const id = (f) => "f_" + f.replace(/^noto-serif-tc-/, "").replace(/-normal\.woff2$/, "").replace(/-/g, "_");
let ts = `// GENERATED by scripts/cjk-subsets.mjs from src/q7/i18n/zh.ts + ext.zh.ts + card.ts — do not edit by hand.\n`;
ts += `// ${chars.length} characters outside the Garamond latin cut → ${out.length} subset files (weights ${WEIGHTS.join(", ")}).\n`;
for (const o of out) ts += `import ${id(o.file)} from "@fontsource/noto-serif-tc/files/${o.file}";\n`;
ts += `\n/** what the bundled EB Garamond (latin cut) draws; everything else in Chinese prose falls to Noto */\n`;
ts += `export const LATIN_RANGE = "${LATIN_RANGE}";\n`;
ts += `\nexport const CJK_FACES: Array<{ url: string; weight: string; unicodeRange: string }> = [\n`;
for (const o of out) ts += `  { url: ${id(o.file)}, weight: "${o.w}", unicodeRange: "${o.range}" },\n`;
ts += `];\n`;
fs.writeFileSync("src/q7/cjkFaces.ts", ts);

let bytes = 0;
for (const o of out) bytes += fs.statSync(path.join(PKG, "files", o.file)).size;
console.log(`${chars.length} chars → ${out.length} files, ${(bytes / 1024).toFixed(1)} KiB`);
for (const o of out) console.log(`  ${o.w}  ${o.file}`);
