"""Custom animation hooks for §1.6 (The Precise Definition of a Limit).

Generated by Claude from the content-script `animation_cue` (CONTENT_METHODOLOGY
§5: custom animations are generated from the natural-language cue, not hand-drawn).
These are STANDALONE, directly-renderable manim scenes for sign-off; the formal
wiring at the storyboard `# HOOK` points lands with the gen-2 hook mechanism
(REBUILD_STATUS task #6). They reuse the pipeline theme + bootstrap so the look
matches the mock film.

Scenes:
  EpsilonDeltaTube      -- §1.6 unit 7 (epsilon_delta_tube), the ANCHOR. Uses a
      convex curve f(x)=½x² (a=2, L=2), NOT a line: with a curve, δ is a genuine
      constraint, so we can dramatize "you pick ε, δ must respond" -- squeeze ε
      and the current δ fails (the active arc poohs out of the narrowed band,
      endpoints flash coral), then shrink δ until the arc is recontained (green).
      A line cannot show this (its corners always sit on the band). Matches the
      textbook fig:precise-limit, which also uses a curve. δ is independent of ε
      (it is FOUND, not a formula) -- that is the lesson.
  BrokenFunctionApproach -- §1.6 unit 3 (the_broken_function). Linear running
      example f(x)=2x-1: two points slide toward x=3, outputs pile at the hole
      (3,5)=the limit, while the solid f(3)=6 sits untouched above.

Run (offline, no TTS):
    .venv\\Scripts\\python video\\animations\\ch01_precise_limit_hooks.py            # both
    .venv\\Scripts\\python video\\animations\\ch01_precise_limit_hooks.py tube        # anchor only
    .venv\\Scripts\\python video\\animations\\ch01_precise_limit_hooks.py approach    # unit 3 only
"""
from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))  # video/ on sys.path
from pipeline import _bootstrap  # noqa: E402
_bootstrap.bootstrap()  # MUST precede any manim import (vendored deps + design fonts)

from manim import (  # noqa: E402
    DOWN, LEFT, RIGHT,
    Axes, Circle, Create, DashedLine, DecimalNumber, Dot, FadeIn, Indicate,
    MathTex, Polygon, Scene, Text, ValueTracker, VGroup, Write, always_redraw,
)

from pipeline.visuals import theme as T  # noqa: E402

# -- anchor (ε-δ tube): a convex curve so δ is a real constraint -----------
CURVE_A, CURVE_L = 2.0, 2.0


def g_curve(x: float) -> float:
    return 0.5 * x * x  # f(2)=2, f'(2)=2 (locally δ≈ε/2, but curvature makes δ smaller)


# -- unit 3 (broken function): the linear running example ------------------
LINE_A, LINE_L = 3.0, 5.0


def f_line(x: float) -> float:
    return 2.0 * x - 1.0


def _palette(scene: Scene):
    scene.camera.background_color = T.color("dark", "bg")
    return {
        "bg": T.color("dark", "bg"),
        "cyan": T.color("dark", "secondary"),
        "coral": T.color("dark", "warning"),
        "gold": T.color("dark", "accent"),
        "green": T.color("dark", "success"),
        "muted": T.color("dark", "muted"),
        "text": T.color("dark", "text"),
        "primary": T.color("dark", "primary"),
    }


def _title(text: str, primary: str) -> Text:
    t = Text(text, font=T.FONT_DISPLAY, font_size=T.fs("h1") * 0.78,
             color=primary, weight="SEMIBOLD")
    t.move_to([-T.FRAME_W / 2 + T.SAFE_MARGIN + t.width / 2,
               T.FRAME_H / 2 - T.SAFE_MARGIN - t.height / 2, 0])
    return t


class EpsilonDeltaTube(Scene):
    def construct(self) -> None:
        c = _palette(self)
        a, L = CURVE_A, CURVE_L
        xmin, xmax, ymin, ymax = 0.0, 4.2, 0.0, 8.0

        axes = Axes(
            x_range=[xmin, xmax, 1], y_range=[ymin, ymax, 2],
            x_length=7.4, y_length=4.9, tips=True,
            axis_config={"color": c["text"], "stroke_width": 2.0,
                         "include_ticks": False, "include_numbers": False},
        ).move_to([0.2, -0.2, 0])

        def p(x, y):
            return axes.c2p(x, y)

        curve = axes.plot(g_curve, x_range=[0.05, 4.0], color=c["cyan"], stroke_width=4)
        curve.set_z_index(2)
        glow = curve.copy().set_stroke(c["cyan"], width=12, opacity=0.16)
        curve_label = MathTex(r"y=f(x)", color=c["cyan"], font_size=T.fs("label"))
        curve_label.move_to(p(3.45, 0.85))

        title = _title("Reading the Definition", c["primary"])

        hole = Circle(radius=0.07, color=c["gold"], stroke_width=3).move_to(p(a, L))
        hole.set_fill(c["bg"], opacity=1.0)
        hole.set_z_index(6)
        L_label = MathTex("L", color=c["text"], font_size=T.fs("label")).next_to(p(xmin, L), LEFT, buff=0.18)

        eps = ValueTracker(1.0)
        dlt = ValueTracker(0.95)  # start deliberately TOO WIDE

        def e() -> float:
            return eps.get_value()

        def d() -> float:
            return dlt.get_value()

        # ε-band: faint horizontal strip + dashed edges
        band = always_redraw(lambda: Polygon(
            p(xmin, L - e()), p(xmax, L - e()), p(xmax, L + e()), p(xmin, L + e()),
            stroke_width=0, fill_color=c["coral"], fill_opacity=0.09).set_z_index(0))
        top = always_redraw(lambda: DashedLine(p(xmin, L + e()), p(xmax, L + e()),
                                               color=c["coral"], stroke_width=2.5, dash_length=0.12).set_z_index(1))
        bot = always_redraw(lambda: DashedLine(p(xmin, L - e()), p(xmax, L - e()),
                                               color=c["coral"], stroke_width=2.5, dash_length=0.12).set_z_index(1))
        # δ-interval: dashed vertical edges
        dleft = always_redraw(lambda: DashedLine(p(a - d(), ymin), p(a - d(), ymax),
                                                 color=c["gold"], stroke_width=2.0, dash_length=0.12).set_z_index(1))
        dright = always_redraw(lambda: DashedLine(p(a + d(), ymin), p(a + d(), ymax),
                                                  color=c["gold"], stroke_width=2.0, dash_length=0.12).set_z_index(1))
        # the ACTIVE ARC: the curve over [a-δ, a+δ] -- the part we must trap
        arc = always_redraw(lambda: axes.plot(
            g_curve, x_range=[a - d(), a + d()], color=c["gold"], stroke_width=7).set_z_index(3))

        # endpoint tells: green when inside the ε-band, coral when poking out
        def right_in() -> bool:
            return g_curve(a + d()) <= L + e() + 1e-6

        def left_in() -> bool:
            return g_curve(a - d()) >= L - e() - 1e-6

        m_right = always_redraw(lambda: Dot(
            p(a + d(), g_curve(a + d())), radius=0.085,
            color=c["green"] if right_in() else c["coral"]).set_z_index(5))
        m_left = always_redraw(lambda: Dot(
            p(a - d(), g_curve(a - d())), radius=0.085,
            color=c["green"] if left_in() else c["coral"]).set_z_index(5))

        # NOTE: no moving "L±ε / a±δ" edge labels -- they collide once the band
        # shrinks (which is the whole point of the animation). The numeric readout
        # below names ε and δ; "L" + the punctured (a,L) anchor the geometry.

        # live readout + the lesson, bottom-centre
        eps_tag = MathTex(r"\varepsilon =", color=c["coral"], font_size=T.fs("step"))
        eps_num = DecimalNumber(e(), num_decimal_places=2, color=c["coral"], font_size=T.fs("step"))
        eps_num.add_updater(lambda m: m.set_value(e()))
        dlt_tag = MathTex(r"\delta =", color=c["gold"], font_size=T.fs("step"))
        dlt_num = DecimalNumber(d(), num_decimal_places=2, color=c["gold"], font_size=T.fs("step"))
        dlt_num.add_updater(lambda m: m.set_value(d()))
        row = VGroup(eps_tag, eps_num, dlt_tag, dlt_num).arrange(buff=0.32)
        caption = MathTex(r"\text{squeeze } \varepsilon \;\Rightarrow\; \delta \text{ must shrink}",
                          color=c["muted"], font_size=T.fs("label"))
        readout = VGroup(row, caption).arrange(DOWN, buff=0.16)
        readout.move_to([0, -T.FRAME_H / 2 + 0.52, 0])

        # -- timeline ------------------------------------------------------
        self.play(Create(axes), run_time=0.9)
        self.play(Create(glow), Create(curve), Write(curve_label), run_time=1.1)
        self.play(FadeIn(title, shift=0.1 * DOWN), run_time=0.5)
        self.play(FadeIn(hole), Write(L_label), run_time=0.6)

        self.add(band, top, bot, dleft, dright, arc, m_left, m_right, readout)
        self.wait(1.3)                                   # δ too wide: arc pokes out, ends coral
        self.play(dlt.animate.set_value(0.42), run_time=2.2)   # find δ: arc drops in, ends green
        self.wait(1.0)
        self.play(eps.animate.set_value(0.5), run_time=1.6)    # squeeze ε: old δ now fails (coral)
        self.wait(0.7)
        self.play(dlt.animate.set_value(0.22), run_time=1.8)   # shrink δ to refit (green)
        self.wait(0.9)
        self.play(eps.animate.set_value(0.25), run_time=1.3)   # squeeze ε again
        self.play(dlt.animate.set_value(0.11), run_time=1.5)   # δ shrinks again
        self.wait(1.6)


class BrokenFunctionApproach(Scene):
    """§1.6 unit 3 (the_broken_function): the limit watches the approach, not f(a).

    Two points slide along y=2x-1 toward x=3 from both sides; their outputs pile
    up at the hole (3, 5) -- the limit -- while the solid point f(3)=6 sits above,
    untouched. Drives "the value at a is irrelevant; the approach gives the limit."
    """

    def construct(self) -> None:
        c = _palette(self)
        a, L = LINE_A, LINE_L
        xmin, ymin, ymax = 0.0, 0.0, 8.0

        axes = Axes(
            x_range=[xmin, 5.0, 1], y_range=[ymin, ymax, 2],
            x_length=7.6, y_length=4.9, tips=True,
            axis_config={"color": c["text"], "stroke_width": 2.0,
                         "include_ticks": False, "include_numbers": False},
        ).move_to([0.15, -0.2, 0])

        def p(x, y):
            return axes.c2p(x, y)

        line = axes.plot(f_line, x_range=[0.4, 4.6], color=c["cyan"], stroke_width=4)
        glow = line.copy().set_stroke(c["cyan"], width=12, opacity=0.16)
        line_label = MathTex(r"y=2x-1", color=c["cyan"], font_size=T.fs("label")).move_to(p(1.05, 2.4))

        title = _title("A Deliberately Broken Function", c["primary"])

        hole = Circle(radius=0.08, color=c["gold"], stroke_width=3).move_to(p(a, L))
        hole.set_fill(c["bg"], opacity=1.0)
        hole.set_z_index(5)
        hole_label = MathTex(r"\lim_{x\to 3} f = 5", color=c["gold"], font_size=T.fs("label"))
        hole_label.next_to(p(a, L), LEFT, buff=0.3)
        solid = Dot(p(a, 6.0), radius=0.08, color=c["coral"]).set_z_index(5)
        solid_label = MathTex(r"f(3)=6", color=c["coral"], font_size=T.fs("label")).next_to(solid, RIGHT, buff=0.22)

        s = ValueTracker(1.45)

        def lx() -> float:
            return a - s.get_value()

        def rx() -> float:
            return a + s.get_value()

        left_dot = always_redraw(lambda: Dot(p(lx(), f_line(lx())), color=c["primary"], radius=0.075).set_z_index(4))
        right_dot = always_redraw(lambda: Dot(p(rx(), f_line(rx())), color=c["primary"], radius=0.075).set_z_index(4))
        left_proj = always_redraw(lambda: DashedLine(
            p(lx(), f_line(lx())), p(xmin, f_line(lx())), color=c["muted"], stroke_width=1.5, dash_length=0.08))
        right_proj = always_redraw(lambda: DashedLine(
            p(rx(), f_line(rx())), p(xmin, f_line(rx())), color=c["muted"], stroke_width=1.5, dash_length=0.08))

        caption = MathTex(r"x \to 3 \quad\Longrightarrow\quad f(x) \to 5",
                          color=c["text"], font_size=T.fs("step"))
        caption.move_to([0, -T.FRAME_H / 2 + T.SAFE_MARGIN + 0.08, 0])

        self.play(Create(axes), run_time=0.9)
        self.play(Create(glow), Create(line), Write(line_label), run_time=1.1)
        self.play(FadeIn(title, shift=0.1 * DOWN), run_time=0.5)
        self.play(FadeIn(hole), Write(hole_label), FadeIn(solid), Write(solid_label), run_time=0.9)
        self.add(left_proj, right_proj, left_dot, right_dot)
        self.play(FadeIn(caption), run_time=0.5)
        self.wait(0.8)
        self.play(s.animate.set_value(0.07), run_time=3.2)
        self.wait(0.6)
        self.play(Indicate(hole, color=c["gold"], scale_factor=1.7), run_time=1.0)
        self.wait(1.2)


SCENES = {
    "tube": ("epsilon_delta_tube_anim", EpsilonDeltaTube),
    "approach": ("the_broken_function_anim", BrokenFunctionApproach),
}


if __name__ == "__main__":
    import sys as _sys
    from manim import tempconfig

    which = _sys.argv[1] if len(_sys.argv) > 1 else "all"
    names = list(SCENES) if which == "all" else [which]
    out_dir = _bootstrap.REPO_ROOT / "video" / "output" / "_anim"
    for _name in names:
        _slug, _cls = SCENES[_name]
        with tempconfig({
            "quality": "low_quality",
            "media_dir": str(out_dir / "_media"),
            "output_file": f"ch01_precise_limit__{_slug}",
            "disable_caching": True,
            "verbosity": "ERROR",
        }):
            _cls().render()
        print(f"[anim] {_name} done")
